export const FACTS = [
  // Psychology & Manipulation
  "Sistem sengaja memberikan kemenangan besar di 2 spin pertama (win-rate 90–98%) untuk memicu dopamin dan membuat Anda ketagihan — teknik yang sama dengan tahap awal kecanduan narkotika.",
  "Fenomena 'Near Miss' (nyaris menang) terjadi 40–65% dari total kekalahan — dirancang algoritmik, bukan kebetulan. Otak meresponsnya hampir sama dengan kemenangan nyata.",
  "Fase Drain aktif: win-rate turun ke 15%. Kemenangan besar dimatikan. Yang tersisa hanyalah 'Loss Disguised as Win' — menang Rp30rb dari taruhan Rp100rb — yang tetap dirayakan sistem dengan suara dan animasi.",
  "Jangan percaya 'pola gacor jam 3 pagi'. Itu konten viral yang diciptakan untuk mendorong deposit. Algoritma slot tidak mengenal waktu atau 'mood'.",
  "Admin situs bisa melihat saldo Anda secara real-time dan mengatur win-rate per pemain kapanpun melalui panel kontrol — tanpa Anda ketahui.",
  "Depo mudah, WD dipersulit. Ini desain intentional: memaksa saldo menang Anda tetap di sistem selama mungkin sampai akhirnya Anda mainkan kembali.",
  "Anda tidak bermain melawan mesin acak. Anda bermain melawan algoritma yang diprogram harus untung — house edge bisa diatur admin hingga 30–50% sewaktu-waktu.",
  "Suara 'jackpot' dan visual yang rame adalah senjata psikologis. Riset menunjukkan audio tertentu meningkatkan impulsivitas bertaruh hingga 24%.",
  "Pernah merasa 'sedikit lagi dapet'? Itu Near Miss Engineering — fitur yang secara khusus diprogram untuk memicu rasa penasaran dan mendorong deposit berikutnya.",
  "Banyak yang hancur karena percaya judi adalah 'jalan pintas'. Faktanya: secara statistik, bermain 100 sesi dengan RTP 70% artinya Anda kehilangan 30% dari total uang yang Anda masukkan.",
  "RTP (Return to Player) 97% di website hanyalah angka marketing — tidak ada audit independen. Di balik layar, admin bisa ubah RTP jadi 40% kapanpun.",
  "Situs judi bukan tempat cari cuan — itu produk hiburan berbayar dengan harga tertinggi: masa depan finansial dan mental Anda.",
  "'Kalau bisa kaya dari judi, nggak ada iklan judi.' Biaya iklan judi online Indonesia mencapai ratusan miliar per tahun — semuanya dibiayai oleh kekalahan pemain.",
  "Uang yang hilang tidak akan kembali lewat judi — setiap sesi baru justru menambah kerugian karena house edge selalu bekerja melawan Anda.",
  "Ingat keluarga di rumah. Data menunjukkan 73% korban judi online mengalami keretakan rumah tangga serius. Taruhan tertinggi bukan uang — melainkan relasi Anda.",

  // Statistics & Facts
  "4,4 juta orang Indonesia terlibat judi online (Setneg RI, 2023). Dari jumlah itu, 80.000+ situs sudah diblokir Kominfo — tapi ribuan baru terus bermunculan setiap bulan.",
  "Perputaran uang judi online Indonesia diestimasi Rp327 triliun per tahun (PPATK). Bandingkan: anggaran pendidikan nasional 2023 sekitar Rp612 triliun.",
  "2,7 juta pemain judi online Indonesia berusia 10–17 tahun. Remaja adalah target utama bandar karena otaknya belum matang dalam menilai risiko jangka panjang.",
  "Rata-rata kerugian korban judi online Indonesia: Rp87 juta per tahun. Setara dengan UMR Jakarta selama 8 bulan, habis tanpa bekas.",
  "Transaksi mencurigakan terkait judi online H1 2023: Rp139 triliun — naik 90% dari tahun sebelumnya (PPATK). Industri ini tumbuh eksponensial.",
  "68% korban judi online memiliki utang pinjol bersamaan. Bandar dan pinjol ilegal seringkali satu ekosistem yang dirancang untuk saling mengunci korban.",
  "Risiko bunuh diri 2,5x lebih tinggi pada pecandu judi dibanding populasi umum (WHO). Kecanduan judi adalah krisis kesehatan mental, bukan sekadar masalah keuangan.",
  "WHO mengklasifikasikan Gambling Disorder sebagai penyakit mental resmi dalam ICD-11 sejak 2019 — setara dengan ketergantungan pada zat adiktif seperti alkohol dan narkoba.",
  "Bonus 'New Member 100%' dengan rollover 30x artinya Anda perlu bertaruh 30x nilai bonus sebelum bisa WD. Secara matematis, hampir mustahil menguntungkan.",
  "Hanya <5% pemain yang akhirnya profit dalam jangka panjang — dan sebagian besar dari mereka adalah pemain profesional poker, bukan slot. Mesin slot tidak pernah bisa dikalahkan secara konsisten.",
];
